apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
namespace: develop  # ネームスペース名
replicas:
  - name: deployment  # metadata.nameを指定。この場合deployment.ymlのmetadata.name
    count: 3