apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: replicaset

spec:
  replicas: 3  # podが3つ作成される
  selector:
    matchLabels:
      tier: replicaset
  template:
    metadata:
      labels:
        tier: replicaset
    spec:
      containers:
      - name: nginx
        image: nginx:1.20