apiVersion: v1
kind: Service
metadata:
  name: service
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: clb
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
  selector:
    app: app

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: loadbalancer-deployment
  labels:
    app: app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
        - name: nginx
          image: nginx:1.20
          ports:
            - containerPort: 80