apiVersion: v1
kind: ConfigMap
metadata:
  name: configmap
data:
  ENV1: "Hello"
  ENV2: "k8s!!"

---
apiVersion: v1
kind: Pod
metadata:
  name: configmap-pod
spec:
  containers:
    - name: nginx
      image: nginx:1.20
      env:
        - name: TEST_ENV1
          valueFrom:
            configMapKeyRef:
              name: configmap
              key: ENV1
        - name: TEST_ENV2
          valueFrom:
            configMapKeyRef:
              name: configmap
              key: ENV2
      volumeMounts:
        - name: volume
          mountPath: "/volume"
          readOnly: true
  volumes:
    - name: volume
      configMap:
        name: configmap