apiVersion: v1
kind: Secret
data:
  secret1: SGVsbG8=
  secret2: S3ViZXJuZXRlcw==
metadata:
  name: secret
type: Opaque

---
apiVersion: v1
kind: Pod
metadata:
  name: secret-pod
spec:

  containers:
    - name: nginx
      image: nginx:1.20
      env:
        - name: MY_SECRET1
          valueFrom:
            secretKeyRef:
              key: secret1
              name: secret

        - name: MY_SECRET2
          valueFrom:
            secretKeyRef:
              key: secret2
              name: secret